# Generated by Django 2.2 on 2022-11-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_submit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyClass',
            fields=[
                ('academy', models.CharField(max_length=20, verbose_name='学院')),
                ('class_name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='专业')),
            ],
            options={
                'verbose_name': '学院专业',
                'verbose_name_plural': '学院专业',
            },
        ),
    ]
