# Generated by Django 2.2 on 2022-11-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPerson',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('sex', models.CharField(max_length=2, verbose_name='性别')),
                ('phone', models.CharField(max_length=15, verbose_name='手机号')),
                ('address', models.TextField(verbose_name='住址')),
                ('activity', models.CharField(max_length=10, verbose_name='活动')),
                ('department', models.CharField(max_length=10, verbose_name='部门')),
                ('department_job', models.CharField(max_length=10, verbose_name='部门职务')),
            ],
            options={
                'verbose_name': '社区人员信息',
                'verbose_name_plural': '社区人员信息表',
            },
        ),
        migrations.CreateModel(
            name='NewPerson',
            fields=[
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('sex', models.CharField(max_length=2, verbose_name='性别')),
                ('phone', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='手机号')),
                ('address', models.TextField(verbose_name='住址')),
                ('activity', models.CharField(max_length=10, verbose_name='活动')),
                ('department', models.CharField(max_length=10, verbose_name='部门')),
                ('changeable', models.CharField(max_length=2, verbose_name='是否接受调剂')),
            ],
            options={
                'verbose_name': '社区新人',
                'verbose_name_plural': '社区新人名单',
            },
        ),
    ]
