# Generated by Django 2.2 on 2022-11-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_auto_20221111_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityperson',
            name='activity',
            field=models.TextField(verbose_name='活动'),
        ),
    ]
